name: Publish Crate


on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
        with:
          cache: true

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run tests
        run: cargo test --all

      - name: Run cargo audit
        run: cargo audit

      - name: Commit Cargo.lock if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Cargo.lock
          git diff --cached --quiet || git commit -m "Update Cargo.lock [skip ci]"

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked